import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import JotaiProvider from './jotai-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next.JS App Router Study',
  description: 'Generated by create next app to study Next.JS App Router',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <JotaiProvider>
          {children}
        </JotaiProvider>
      </body>
    </html>
  )
}
